# Generated by Django 4.2.23 on 2025-07-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nombre del empleado', max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(help_text='Apellido del empleado', max_length=50, verbose_name='Apellido')),
                ('date_of_birth', models.DateField(help_text='Fecha de nacimiento del empleado', verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], help_text='Género del empleado', max_length=1, verbose_name='Género')),
                ('marital_status', models.CharField(choices=[('single', 'Soltero/a'), ('married', 'Casado/a'), ('divorced', 'Divorciado/a'), ('widowed', 'Viudo/a')], help_text='Estado civil del empleado', max_length=20, verbose_name='Estado Civil')),
                ('phone', models.CharField(help_text='Número de teléfono del empleado', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(help_text='Correo electrónico del empleado', max_length=254, verbose_name='Correo Electrónico')),
                ('address', models.TextField(help_text='Dirección completa del empleado', verbose_name='Dirección')),
                ('city', models.CharField(help_text='Ciudad donde reside el empleado', max_length=100, verbose_name='Ciudad')),
                ('employee_id', models.CharField(help_text='Identificador único del empleado', max_length=20, unique=True, verbose_name='ID de Empleado')),
                ('position', models.CharField(help_text='Cargo o posición del empleado', max_length=100, verbose_name='Cargo')),
                ('department', models.CharField(help_text='Departamento donde trabaja el empleado', max_length=100, verbose_name='Departamento')),
                ('hire_date', models.DateField(help_text='Fecha en que fue contratado el empleado', verbose_name='Fecha de Contratación')),
                ('employment_status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido'), ('terminated', 'Terminado')], default='active', help_text='Estado actual del empleado', max_length=20, verbose_name='Estado de Empleo')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Salario mensual del empleado', max_digits=10, verbose_name='Salario')),
                ('work_schedule', models.CharField(help_text='Horario de trabajo del empleado (ej: L-V 8:00-16:00)', max_length=100, verbose_name='Horario de Trabajo')),
                ('shift_type', models.CharField(help_text='Tipo de turno (mañana, tarde, noche, rotativo)', max_length=50, verbose_name='Tipo de Turno')),
                ('emergency_contact_name', models.CharField(help_text='Nombre del contacto de emergencia', max_length=100, verbose_name='Contacto de Emergencia')),
                ('emergency_contact_relationship', models.CharField(help_text='Relación con el contacto de emergencia', max_length=50, verbose_name='Relación')),
                ('emergency_contact_phone', models.CharField(help_text='Teléfono del contacto de emergencia', max_length=20, verbose_name='Teléfono de Emergencia')),
                ('blood_type', models.CharField(blank=True, help_text='Tipo de sangre del empleado', max_length=5, verbose_name='Tipo de Sangre')),
                ('allergies', models.TextField(blank=True, help_text='Alergias conocidas del empleado', verbose_name='Alergias')),
                ('medical_conditions', models.TextField(blank=True, help_text='Condiciones médicas relevantes', verbose_name='Condiciones Médicas')),
                ('skills', models.TextField(blank=True, help_text='Habilidades y certificaciones del empleado', verbose_name='Habilidades')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el empleado', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
