# Generated by Django 4.2.23 on 2025-07-27 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Primer nombre del residente",
                        max_length=50,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Apellido del residente",
                        max_length=50,
                        verbose_name="Apellido",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        help_text="Fecha de nacimiento del residente",
                        verbose_name="Fecha de Nacimiento",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        help_text="Género del residente",
                        max_length=1,
                        verbose_name="Género",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Número de teléfono del residente",
                        max_length=20,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Dirección de correo electrónico del residente",
                        max_length=254,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Dirección de residencia anterior",
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Ciudad de residencia anterior",
                        max_length=100,
                        verbose_name="Ciudad",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Soltero/a"),
                            ("married", "Casado/a"),
                            ("divorced", "Divorciado/a"),
                            ("widowed", "Viudo/a"),
                            ("separated", "Separado/a"),
                        ],
                        help_text="Estado civil del residente",
                        max_length=20,
                        verbose_name="Estado Civil",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        help_text="Ocupación anterior del residente",
                        max_length=100,
                        verbose_name="Ocupación",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de sangre del residente",
                        max_length=5,
                        verbose_name="Tipo de Sangre",
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True,
                        help_text="Lista de alergias conocidas",
                        verbose_name="Alergias",
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Condiciones médicas crónicas o importantes",
                        verbose_name="Condiciones Médicas",
                    ),
                ),
                (
                    "medications",
                    models.TextField(
                        blank=True,
                        help_text="Medicamentos que toma regularmente",
                        verbose_name="Medicamentos",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        help_text="Nombre completo del contacto de emergencia",
                        max_length=100,
                        verbose_name="Nombre del Contacto de Emergencia",
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Cónyuge"),
                            ("child", "Hijo/a"),
                            ("parent", "Padre/Madre"),
                            ("sibling", "Hermano/a"),
                            ("friend", "Amigo/a"),
                            ("other", "Otro"),
                        ],
                        help_text="Relación del contacto de emergencia con el residente",
                        max_length=20,
                        verbose_name="Relación con el Contacto de Emergencia",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        help_text="Número de teléfono del contacto de emergencia",
                        max_length=20,
                        verbose_name="Teléfono del Contacto de Emergencia",
                    ),
                ),
                (
                    "emergency_contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Correo electrónico del contacto de emergencia",
                        max_length=254,
                        verbose_name="Correo del Contacto de Emergencia",
                    ),
                ),
                (
                    "admission_date",
                    models.DateField(
                        help_text="Fecha en que el residente fue admitido",
                        verbose_name="Fecha de Admisión",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre el residente",
                        verbose_name="Notas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Habitación asignada al residente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="facilities.room",
                        verbose_name="Habitación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Residente",
                "verbose_name_plural": "Residentes",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="residents_r_last_na_09bdf2_idx",
                    ),
                    models.Index(
                        fields=["admission_date"], name="residents_r_admissi_6ad416_idx"
                    ),
                    models.Index(
                        fields=["room"], name="residents_r_room_id_85b6bb_idx"
                    ),
                ],
            },
        ),
    ]
