# Generated by Django 4.2.23 on 2025-07-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="is_in_treatment",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el residente está actualmente en tratamiento médico",
                verbose_name="En Tratamiento",
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="treatment_notes",
            field=models.TextField(
                blank=True,
                help_text="Notas adicionales sobre el tratamiento actual",
                verbose_name="Notas del Tratamiento",
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="treatment_start_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha en que comenzó el tratamiento actual",
                null=True,
                verbose_name="Fecha de Inicio del Tratamiento",
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="treatment_type",
            field=models.CharField(
                blank=True,
                help_text="Tipo de tratamiento que está recibiendo (ej: fisioterapia, terapia ocupacional, etc.)",
                max_length=50,
                verbose_name="Tipo de Tratamiento",
            ),
        ),
    ]
