# Generated by Django 4.2.23 on 2025-07-28 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "residents",
            "0002_resident_is_in_treatment_resident_treatment_notes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ResidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                            ("custom", "Personalizado"),
                        ],
                        default="monthly",
                        help_text="Tipo de informe periódico",
                        max_length=20,
                        verbose_name="Tipo de Informe",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        help_text="Fecha en que se realiza el informe",
                        verbose_name="Fecha del Informe",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("completed", "Completado"),
                            ("archived", "Archivado"),
                        ],
                        default="draft",
                        help_text="Estado actual del informe",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "physical_condition",
                    models.TextField(
                        blank=True,
                        help_text="Evaluación del estado físico del residente",
                        verbose_name="Estado Físico",
                    ),
                ),
                (
                    "mental_condition",
                    models.TextField(
                        blank=True,
                        help_text="Evaluación del estado mental y emocional",
                        verbose_name="Estado Mental",
                    ),
                ),
                (
                    "social_activity",
                    models.TextField(
                        blank=True,
                        help_text="Participación en actividades sociales y recreativas",
                        verbose_name="Actividad Social",
                    ),
                ),
                (
                    "medical_treatment",
                    models.TextField(
                        blank=True,
                        help_text="Información sobre tratamientos médicos actuales",
                        verbose_name="Tratamiento Médico",
                    ),
                ),
                (
                    "medication_changes",
                    models.TextField(
                        blank=True,
                        help_text="Cambios en la medicación durante el período",
                        verbose_name="Cambios en Medicación",
                    ),
                ),
                (
                    "incidents",
                    models.TextField(
                        blank=True,
                        help_text="Incidentes o eventos importantes durante el período",
                        verbose_name="Incidentes",
                    ),
                ),
                (
                    "goals_achieved",
                    models.TextField(
                        blank=True,
                        help_text="Metas alcanzadas durante el período",
                        verbose_name="Metas Alcanzadas",
                    ),
                ),
                (
                    "next_goals",
                    models.TextField(
                        blank=True,
                        help_text="Metas para el próximo período",
                        verbose_name="Próximas Metas",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Recomendaciones para el cuidado del residente",
                        verbose_name="Recomendaciones",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Usuario que creó el informe",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        help_text="Residente al que pertenece este informe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="residents.resident",
                        verbose_name="Residente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informe de Residente",
                "verbose_name_plural": "Informes de Residentes",
                "ordering": ["-report_date", "-created_at"],
                "unique_together": {("resident", "report_date", "report_type")},
            },
        ),
    ]
