# Generated by Django 4.2.23 on 2025-07-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0003_residentreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="treatment_end_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha en que finalizó o se espera que finalice el tratamiento",
                null=True,
                verbose_name="Fecha de Finalización del Tratamiento",
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="treatment_frequency",
            field=models.CharField(
                blank=True,
                help_text="Frecuencia del tratamiento (ej: diario, 3 veces por semana, etc.)",
                max_length=50,
                verbose_name="Frecuencia del Tratamiento",
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="treatment_goals",
            field=models.TextField(
                blank=True,
                help_text="Objetivos específicos del tratamiento actual",
                verbose_name="Objetivos del Tratamiento",
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="treatment_progress",
            field=models.TextField(
                blank=True,
                help_text="Evaluación del progreso del tratamiento",
                verbose_name="Progreso del Tratamiento",
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="treatment_provider",
            field=models.CharField(
                blank=True,
                help_text="Nombre del profesional o institución que proporciona el tratamiento",
                max_length=100,
                verbose_name="Proveedor del Tratamiento",
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="treatment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Activo"),
                    ("completed", "Completado"),
                    ("suspended", "Suspendido"),
                    ("discontinued", "Discontinuado"),
                    ("maintenance", "Mantenimiento"),
                    ("evaluation", "En Evaluación"),
                ],
                help_text="Estado actual del tratamiento",
                max_length=20,
                verbose_name="Estado del Tratamiento",
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="treatment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("physical_therapy", "Fisioterapia"),
                    ("occupational_therapy", "Terapia Ocupacional"),
                    ("speech_therapy", "Terapia del Habla"),
                    ("psychological_therapy", "Terapia Psicológica"),
                    ("medical_treatment", "Tratamiento Médico"),
                    ("rehabilitation", "Rehabilitación"),
                    ("pain_management", "Manejo del Dolor"),
                    ("cardiac_rehabilitation", "Rehabilitación Cardíaca"),
                    ("respiratory_therapy", "Terapia Respiratoria"),
                    ("nutritional_therapy", "Terapia Nutricional"),
                    ("social_work", "Trabajo Social"),
                    ("recreational_therapy", "Terapia Recreativa"),
                    ("cognitive_therapy", "Terapia Cognitiva"),
                    ("other", "Otro"),
                ],
                help_text="Tipo específico de tratamiento que está recibiendo",
                max_length=50,
                verbose_name="Tipo de Tratamiento",
            ),
        ),
    ]
