# Generated by Django 4.2.23 on 2025-07-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="occupied_beds",
        ),
    ]
