# Generated by Django 4.2.23 on 2025-08-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="format",
            field=models.CharField(
                choices=[("csv", "CSV")],
                default="csv",
                max_length=10,
                verbose_name="Formato",
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="default_format",
            field=models.CharField(
                choices=[("csv", "CSV")],
                default="csv",
                max_length=10,
                verbose_name="Formato por Defecto",
            ),
        ),
    ]
