# Generated by Django 4.2.23 on 2025-07-27 02:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("expense", "Gasto"),
                            ("income", "Ingreso"),
                            ("investment", "Inversión"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3498db",
                        help_text="Color en formato hexadecimal",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["category_type", "name"],
                "unique_together": {("name", "category_type")},
            },
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "investment_type",
                    models.CharField(
                        choices=[
                            ("equipment", "Equipamiento"),
                            ("infrastructure", "Infraestructura"),
                            ("technology", "Tecnología"),
                            ("marketing", "Marketing"),
                            ("training", "Capacitación"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Inversión",
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha Planificada",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Inicio"
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Finalización"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planificado"),
                            ("in_progress", "En Progreso"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Porcentaje de Progreso",
                    ),
                ),
                (
                    "expected_roi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="ROI Esperado (%)",
                    ),
                ),
                (
                    "expected_benefits",
                    models.TextField(blank=True, verbose_name="Beneficios Esperados"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        limit_choices_to={"category_type": "investment"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inversión",
                "verbose_name_plural": "Inversiones",
                "ordering": ["-planned_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "income_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Ingreso",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Pago"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("card", "Tarjeta"),
                            ("transfer", "Transferencia"),
                            ("check", "Cheque"),
                            ("other", "Otro"),
                        ],
                        default="transfer",
                        max_length=20,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("received", "Recibido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Cliente"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número de Factura"
                    ),
                ),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True,
                        upload_to="financial/receipts/",
                        verbose_name="Comprobante",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        limit_choices_to={"category_type": "income"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingreso",
                "verbose_name_plural": "Ingresos",
                "ordering": ["-income_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Gasto",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Pago"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("card", "Tarjeta"),
                            ("transfer", "Transferencia"),
                            ("check", "Cheque"),
                            ("other", "Otro"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("paid", "Pagado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Proveedor"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número de Factura"
                    ),
                ),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True,
                        upload_to="financial/receipts/",
                        verbose_name="Comprobante",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        limit_choices_to={"category_type": "expense"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                            ("yearly", "Anual"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Período",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de Fin")),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Presupuesto Total",
                    ),
                ),
                (
                    "allocated_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Presupuesto Asignado",
                    ),
                ),
                (
                    "spent_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Presupuesto Gastado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CashFlow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[("inflow", "Entrada"), ("outflow", "Salida")],
                        max_length=10,
                        verbose_name="Tipo de Flujo",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo Inicial",
                    ),
                ),
                (
                    "total_inflow",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Entradas",
                    ),
                ),
                (
                    "total_outflow",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Salidas",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo Final",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "expenses",
                    models.ManyToManyField(
                        blank=True, to="financial.expense", verbose_name="Gastos"
                    ),
                ),
                (
                    "incomes",
                    models.ManyToManyField(
                        blank=True, to="financial.income", verbose_name="Ingresos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Flujo de Caja",
                "verbose_name_plural": "Flujos de Caja",
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
    ]
