# Generated by Django 4.2.23 on 2025-07-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent string from the request', null=True),
        ),
    ]
