# Generated by Django 4.2.23 on 2025-07-26 22:35

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_audittrail_user_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="Token for password reset (encrypted)", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_created",
            field=models.DateTimeField(
                blank=True, help_text="When password reset token was created", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_expires",
            field=models.DateTimeField(
                blank=True, help_text="When password reset token expires", null=True
            ),
        ),
    ]
